In [1]:
import math
import functools  # Import this to use reduce
import numpy as np

map() func

In [2]:
mylist = [1,64,125,256]

result = map(math.sqrt, mylist)     # map: applies the given method to each element in the list
list(result)

[1.0, 8.0, 11.180339887498949, 16.0]

join() func

In [3]:
# Convert each item's data type to str
mylist_str = map(str, mylist)

#list(mylist_str)

In [4]:
mylist_str = ' '.join(mylist_str)
mylist_str

'1 64 125 256'

filter() func

In [5]:
def isEven(num):
    return num%2==0

even = filter(isEven,mylist)  # Returns the list of elements which return true for the given func.

list(even)

[64, 256]

reduce() func

In [6]:
def multiply(number1, number2):
    return number1 * number2

mylist=[1,2,3,4,5]
# reduce applies the given function to each element and accumulates the result
functools.reduce(multiply,mylist)

120

zip() func

In [7]:
cities=["Ankara","Istanbul","Izmir","Bursa"]
codes=["06","34","35","16"]

result = zip(cities,codes)
list(result)

[('Ankara', '06'), ('Istanbul', '34'), ('Izmir', '35'), ('Bursa', '16')]

In [8]:
mydictionary = dict(zip(cities,codes))
mydictionary

{'Ankara': '06', 'Istanbul': '34', 'Izmir': '35', 'Bursa': '16'}

Lambda

In [9]:
lambda x, y: (x+y)/2

<function __main__.<lambda>(x, y)>

In [12]:
avg = lambda x, y: (x+y)/2

print("Data type of avg: ", type(avg))
avg(16,14)

Data type of avg:  <class 'function'>


15.0

In [13]:
nums=[2, 4, 6, 16, 20]

squares = map(lambda num: num**2,nums)

list(squares)

[4, 16, 36, 256, 400]

In [14]:
def pow(n):
    return lambda y: math.pow(y,n)

cube = pow(3)

cube(2)

8.0

#### Numpy Array Control

In [21]:
my_array = np.array([4, 6, 8, 5, 3, 7])

cond_array = (my_array > 6)

cond_array

array([False, False,  True, False, False,  True])

In [22]:
my_array[my_array > 6]
# OR you can use
my_array[cond_array]

array([8, 7])

In [24]:
my_array[[1,3]] # Return elements of just 1st and 3rd index

array([6, 5])

In [26]:
my_array[1:3]   # Return elements between 1st and 3rd index (returns 1st and 2nd)

array([6, 8])

In [27]:
my_array[-1]    # Return elements between 1st and 3rd index (returns 1st and 2nd)

7

In [29]:
my_array[1:4:2]  # Return elements between 1st and 4th index with 2 element interval

array([6, 5])

In [30]:
my_array[::2]    # Return all elements with 2 element interval

array([4, 8, 3])

In [31]:
my_array_int = my_array.astype('i')   # Convert each items data type to the new data type
my_array_int

array([4, 6, 8, 5, 3, 7], dtype=int32)

In [36]:
mycopy = my_array_int.copy()   # Copy the content of the array, if you change the elements of the copied array it does not effect the original array

mycopy[0] = 2

print("mycopy:       ", mycopy)
print("my_array_int: ", my_array_int)

mycopy:        [2 6 8 5 3 7]
my_array_int:  [4 6 8 5 3 7]


In [38]:
mycopy = my_array_int.view()   # Original view of the array (reference), if you change the elements of the viewed array it effects the original array

mycopy[0] = 9

print("mycopy:       ", mycopy)
print("my_array_int: ", my_array_int)

mycopy:        [9 6 8 5 3 7]
my_array_int:  [9 6 8 5 3 7]


Multi Dimensional Array

In [40]:
npmulti = np.array([[10,20,30],[40,50,60]])

print("npmulti.shape: ", npmulti.shape)   # The number of elements in each dimension
npmulti

npmulti.shape:  (2, 3)


array([[10, 20, 30],
       [40, 50, 60]])

In [44]:
# Creating array with diferent size of members in indexes
npmulti2 = np.array([[10,20,30],[40,50,60,30]])
print("npmulti2.shape: ", npmulti2.shape)
npmulti2

npmulti2.shape:  (2,)


<ipython-input-44-b498a6addc56>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  npmulti2 = np.array([[10,20,30],[40,50,60,30]])


array([list([10, 20, 30]), list([40, 50, 60, 30])], dtype=object)

In [46]:
npmulti.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [47]:
npmulti.reshape(-1)  # Flaten the array

array([10, 20, 30, 40, 50, 60])

np.nditer() func

In [48]:
for x in np.nditer(npmulti):    # Iterate each element in the given array
    print(x)

10
20
30
40
50
60


np.ndenumerate() func

In [49]:
for (x,y) in np.ndenumerate(npmulti):
    print(x,y)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(1, 0) 40
(1, 1) 50
(1, 2) 60


In [62]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])

print("array1.shape", array1.shape)
print("array2.shape", array2.shape)

array1.shape (2, 2)
array2.shape (2, 2)


np.concatenate() func

In [63]:
np.concatenate((array1,array2), axis=0)    # axis - row wise concatenate 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
np.concatenate((array1,array2), axis=1)    # axis - column wise concatenate 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [65]:
np.concatenate((array1,array2), axis=None)  # flaten concatenate

array([1, 2, 3, 4, 5, 6, 7, 8])

np.stack() func

In [66]:
row_stck = np.stack((array1,array2), axis=0)  # First dimension
print("row_stck.shape", row_stck.shape)
row_stck

row_stck.shape (2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [67]:
np.stack((array1,array2), axis=1)    # Second dimension

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [70]:
np.stack((array1,array2), axis=-1)   # Last dimension

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [73]:
np.stack((array1,array2), axis=2)

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [69]:
np.array([[[9]]]).shape

(1, 1, 1)

np.hstack() func

In [74]:
np.hstack((array1,array2))   # Horizantally

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

np.vstack() func

In [75]:
np.vstack((array1,array2))   # Vertically

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

np.dstack() func

In [76]:
np.dstack((array1,array2))  # Stack arrays in sequence depth wise (along a third axis)
# to concatenation along the third axis after 2-D arrays
# of shape `(M,N)` have been reshaped to `(M,N,1)` and 1-D arrays of shape
#`(N,)` have been reshaped to `(1,N,1)`.

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

np.array_split() func

In [78]:
np.array_split(np.array([1,2,3,4,5,6]), 2)

[array([1, 2, 3]), array([4, 5, 6])]

In [79]:
np.array_split(np.array([1,2,3,4,5,6]), 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [80]:
np.array_split(np.array([1,2,3,4,5,6]), 4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

np.where() func

In [98]:
myarray = np.array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

new_list = np.where(myarray > 6)    # np.where() function returns indexes of the elements that obeys the condition
new_list

(array([0, 1, 2, 3]),)

In [97]:
new_list = myarray[myarray > 6]    # It returns elements that obeys the condition
new_list

array([10,  9,  8,  7])

In [99]:
np.where(myarray % 2 == 0)

(array([0, 2, 4, 6, 8]),)

np.char.index() func

In [100]:
fruits=np.array(["mango","banana","apple","orange"])

fruits[np.char.index(fruits, sub='a') == 1]    # Returns elements that 2nd character is 'a' (element index:1)

array(['mango', 'banana'], dtype='<U6')

In [102]:
fruits[fruits == 'banana']

array(['banana'], dtype='<U6')

np.random.normal() func

In [103]:
np.random.normal(50,10,20) # mean, standard dev. number of instances

array([49.21783341, 47.87039112, 54.59666606, 29.51637321, 47.23047052,
       29.90296929, 57.73339644, 48.44832556, 55.5760567 , 44.40595063,
       43.18760754, 51.97102956, 52.51288301, 56.44260501, 58.14659978,
       36.16517876, 52.78669955, 49.01577625, 49.50209852, 61.67949097])

np.corrcoef() func

In [104]:
citizen_weight = np.round(np.random.normal(65,20,20), 2)
citizen_height = np.round(np.random.normal(1.65,0.3,20), 2)

np.corrcoef(citizen_height,citizen_weight)

array([[ 1.        , -0.09049068],
       [-0.09049068,  1.        ]])

In [105]:
citizen_weight

array([53.21, 72.49, 80.77, 90.54, 65.14, 36.8 , 81.69, 36.75, 90.12,
       77.2 , 54.43, 49.79, 81.02, 68.21, 93.39, 90.4 , 82.  , 57.58,
       65.85, 45.9 ])

In [106]:
citizen_height

array([1.85, 1.97, 1.63, 1.81, 1.67, 2.33, 2.03, 1.69, 2.24, 1.48, 1.45,
       2.31, 1.4 , 1.24, 2.22, 1.15, 1.62, 1.51, 1.82, 1.51])

np.column_stack() func

In [108]:
citizen = np.column_stack((citizen_height,citizen_weight))
citizen

array([[ 1.85, 53.21],
       [ 1.97, 72.49],
       [ 1.63, 80.77],
       [ 1.81, 90.54],
       [ 1.67, 65.14],
       [ 2.33, 36.8 ],
       [ 2.03, 81.69],
       [ 1.69, 36.75],
       [ 2.24, 90.12],
       [ 1.48, 77.2 ],
       [ 1.45, 54.43],
       [ 2.31, 49.79],
       [ 1.4 , 81.02],
       [ 1.24, 68.21],
       [ 2.22, 93.39],
       [ 1.15, 90.4 ],
       [ 1.62, 82.  ],
       [ 1.51, 57.58],
       [ 1.82, 65.85],
       [ 1.51, 45.9 ]])

np.dot() func

In [115]:
matrixA = np.array([[1,2,3],[4,5,6]])
matrixB = np.array([[7,8],[9,10],[11,12]])

np.dot(matrixA,matrixB)   # Dot product of two arrays (matrix multiplication)

array([[ 58,  64],
       [139, 154]])

In [116]:
matrixC = np.array([[1,2,3],[4,5,6]])
matrixD = np.array([[7,8,9],[10,11,12]])

np.multiply(matrixC,matrixD)   # Multiply arguments element-wise.

array([[ 7, 16, 27],
       [40, 55, 72]])

np.transpose() func

In [117]:
np.transpose(matrixA)
# OR
matrixA.T

array([[1, 4],
       [2, 5],
       [3, 6]])

np.linalg.det()

In [122]:
np.linalg.det(np.dot(matrixA,matrixB))   # Compute the determinant of an array.

36.00000000000032

np.linalg.inv()

In [123]:
np.linalg.inv(np.dot(matrixA,matrixB))   # Compute the (multiplicative) inverse of a matrix. 

array([[ 4.27777778, -1.77777778],
       [-3.86111111,  1.61111111]])

np.identity()

In [124]:
identityMatrix = np.identity(3)
identityMatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

np.zeros()

In [125]:
zeroMatrix = np.zeros([2,5])
zeroMatrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [126]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [135]:
img_array = np.array([
[
[[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5]],
[[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5]],
[[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5]],
[[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5]],
[[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5]],
[[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5]]
],
[
[[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5]],
[[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5]],
[[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5]],
[[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5]],
[[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5]],
[[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5]]
]])
img_array.shape    # This is 6x8 RGB image pair (It consists of two different images)

(2, 6, 8, 3)

In [184]:
IMG_SIZE = (6,8)

In [193]:
first_img = img_array[0]
first_img.shape

(6, 8, 3)

In [210]:
def get_img_color(img, size, color=0):     # This function returns a reshaped image array that has only one color option for RGB images 
    color_arr = np.zeros(size)
    img = np.array(img)

    # "color" argument is an index of color that represents the color element of the image (R, G, B)
    pixel_cnt = 0  # Pixel of the iamge
    color_ix = 0   # Color index of the pixel

    if len(img.shape) > 3:    # (Row, Column, Color)
        return color_arr
    elif len(img.shape) == 2: # (Row, Column)  -  Already one color 
        return img

    for pixel in img:
        for ind in pixel:
            color_arr[pixel_cnt][color_ix] = ind[color]
            color_ix += 1
        pixel_cnt += 1
        color_ix = 0

    return color_arr

In [211]:
first_img_r = get_img_color(first_img, IMG_SIZE, 1)
first_img_r

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [213]:
first_img_r = get_img_color(first_img_r, IMG_SIZE, 1)   # first_img_r is already one color array
first_img_r

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])