In [1]:
import math
import functools  # Import this to use reduce
import numpy as np

map() func

In [2]:
mylist = [1,64,125,256]

result = map(math.sqrt, mylist)     # map: applies the given method to each element in the list
list(result)

[1.0, 8.0, 11.180339887498949, 16.0]

join() func

In [3]:
# Convert each item's data type to str
mylist_str = map(str, mylist)

#list(mylist_str)

In [4]:
mylist_str = ' '.join(mylist_str)
mylist_str

'1 64 125 256'

filter() func

In [5]:
def isEven(num):
    return num%2==0

even = filter(isEven,mylist)  # Returns the list of elements which return true for the given func.

list(even)

[64, 256]

reduce() func

In [6]:
def multiply(number1, number2):
    return number1 * number2

mylist=[1,2,3,4,5]
# reduce applies the given function to each element and accumulates the result
functools.reduce(multiply,mylist)

120

zip() func

In [7]:
cities=["Ankara","Istanbul","Izmir","Bursa"]
codes=["06","34","35","16"]

result = zip(cities,codes)
list(result)

[('Ankara', '06'), ('Istanbul', '34'), ('Izmir', '35'), ('Bursa', '16')]

In [8]:
mydictionary = dict(zip(cities,codes))
mydictionary

{'Ankara': '06', 'Istanbul': '34', 'Izmir': '35', 'Bursa': '16'}

Lambda

In [9]:
lambda x, y: (x+y)/2

<function __main__.<lambda>(x, y)>

In [10]:
avg = lambda x, y: (x+y)/2

print("Data type of avg: ", type(avg))
avg(16,14)

Data type of avg:  <class 'function'>


15.0

In [11]:
nums=[2, 4, 6, 16, 20]

squares = map(lambda num: num**2,nums)

list(squares)

[4, 16, 36, 256, 400]

In [12]:
def pow(n):
    return lambda y: math.pow(y,n)

cube = pow(3)

cube(2)

8.0

#### Numpy Array Control

In [13]:
my_array = np.array([4, 6, 8, 5, 3, 7])

cond_array = (my_array > 6)

cond_array

array([False, False,  True, False, False,  True])

In [14]:
my_array[my_array > 6]
# OR you can use
my_array[cond_array]

array([8, 7])

In [15]:
my_array[[1,3]] # Return elements of just 1st and 3rd index

array([6, 5])

In [16]:
my_array[1:3]   # Return elements between 1st and 3rd index (returns 1st and 2nd)

array([6, 8])

In [17]:
my_array[-1]    # Return elements between 1st and 3rd index (returns 1st and 2nd)

7

In [18]:
my_array[1:4:2]  # Return elements between 1st and 4th index with 2 element interval

array([6, 5])

In [19]:
my_array[::2]    # Return all elements with 2 element interval

array([4, 8, 3])

In [20]:
my_array_int = my_array.astype('i')   # Convert each items data type to the new data type
my_array_int

array([4, 6, 8, 5, 3, 7], dtype=int32)

In [21]:
mycopy = my_array_int.copy()   # Copy the content of the array, if you change the elements of the copied array it does not effect the original array

mycopy[0] = 2

print("mycopy:       ", mycopy)
print("my_array_int: ", my_array_int)

mycopy:        [2 6 8 5 3 7]
my_array_int:  [4 6 8 5 3 7]


In [22]:
mycopy = my_array_int.view()   # Original view of the array (reference), if you change the elements of the viewed array it effects the original array

mycopy[0] = 9

print("mycopy:       ", mycopy)
print("my_array_int: ", my_array_int)

mycopy:        [9 6 8 5 3 7]
my_array_int:  [9 6 8 5 3 7]


Multi Dimensional Array

In [23]:
npmulti = np.array([[10,20,30],[40,50,60]])

print("npmulti.shape: ", npmulti.shape)   # The number of elements in each dimension
npmulti

npmulti.shape:  (2, 3)


array([[10, 20, 30],
       [40, 50, 60]])

In [24]:
# Creating array with diferent size of members in indexes
npmulti2 = np.array([[10,20,30],[40,50,60,30]])
print("npmulti2.shape: ", npmulti2.shape)
npmulti2

npmulti2.shape:  (2,)


<ipython-input-24-b498a6addc56>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  npmulti2 = np.array([[10,20,30],[40,50,60,30]])


array([list([10, 20, 30]), list([40, 50, 60, 30])], dtype=object)

In [25]:
npmulti.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [26]:
npmulti.reshape(-1)  # Flaten the array

array([10, 20, 30, 40, 50, 60])

np.nditer() func

In [27]:
for x in np.nditer(npmulti):    # Iterate each element in the given array
    print(x)

10
20
30
40
50
60


np.ndenumerate() func

In [28]:
for (x,y) in np.ndenumerate(npmulti):
    print(x,y)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(1, 0) 40
(1, 1) 50
(1, 2) 60


In [29]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])

print("array1.shape", array1.shape)
print("array2.shape", array2.shape)

array1.shape (2, 2)
array2.shape (2, 2)


np.concatenate() func

In [30]:
np.concatenate((array1,array2), axis=0)    # axis - row wise concatenate

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [31]:
np.concatenate((array1,array2), axis=1)    # axis - column wise concatenate

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
np.concatenate((array1,array2), axis=None)  # flaten concatenate

array([1, 2, 3, 4, 5, 6, 7, 8])

np.stack() func

In [33]:
row_stck = np.stack((array1,array2), axis=0)  # First dimension
print("row_stck.shape", row_stck.shape)
row_stck

row_stck.shape (2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
np.stack((array1,array2), axis=1)    # Second dimension

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [35]:
np.stack((array1,array2), axis=-1)   # Last dimension

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [36]:
np.stack((array1,array2), axis=2)

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [37]:
np.array([[[9]]]).shape

(1, 1, 1)

np.hstack() func

In [38]:
np.hstack((array1,array2))   # Horizantally

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

np.vstack() func

In [39]:
np.vstack((array1,array2))   # Vertically

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

np.dstack() func

In [40]:
np.dstack((array1,array2))  # Stack arrays in sequence depth wise (along a third axis)
# to concatenation along the third axis after 2-D arrays
# of shape `(M,N)` have been reshaped to `(M,N,1)` and 1-D arrays of shape
#`(N,)` have been reshaped to `(1,N,1)`.

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

np.array_split() func

In [41]:
np.array_split(np.array([1,2,3,4,5,6]), 2)

[array([1, 2, 3]), array([4, 5, 6])]

In [42]:
np.array_split(np.array([1,2,3,4,5,6]), 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [43]:
np.array_split(np.array([1,2,3,4,5,6]), 4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

np.where() func

In [44]:
myarray = np.array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

new_list = np.where(myarray > 6)    # np.where() function returns indexes of the elements that obeys the condition
new_list

(array([0, 1, 2, 3]),)

In [45]:
new_list = myarray[myarray > 6]    # It returns elements that obeys the condition
new_list

array([10,  9,  8,  7])

In [46]:
np.where(myarray % 2 == 0)

(array([0, 2, 4, 6, 8]),)

np.char.index() func

In [47]:
fruits=np.array(["mango","banana","apple","orange"])

fruits[np.char.index(fruits, sub='a') == 1]    # Returns elements that 2nd character is 'a' (element index:1)

array(['mango', 'banana'], dtype='<U6')

In [48]:
fruits[fruits == 'banana']

array(['banana'], dtype='<U6')

np.random.normal() func

In [49]:
np.random.normal(50,10,20) # mean, standard dev. number of instances

array([43.41419267, 37.55858869, 44.22167351, 44.28922967, 44.59312602,
       35.05713885, 44.26852354, 47.3339957 , 46.8397682 , 51.34528023,
       69.5867351 , 50.78418218, 42.88031252, 57.85130816, 45.66479339,
       35.06491524, 44.92863782, 76.23467479, 50.17555407, 64.71137197])

np.corrcoef() func

In [50]:
citizen_weight = np.round(np.random.normal(65,20,20), 2)
citizen_height = np.round(np.random.normal(1.65,0.3,20), 2)

np.corrcoef(citizen_height,citizen_weight)

array([[ 1.        , -0.09312051],
       [-0.09312051,  1.        ]])

In [51]:
citizen_weight

array([ 47.41,  28.15,  92.41, 117.85,  88.32,  20.4 ,  48.34,  39.04,
        74.86,  89.01,  70.84,  64.15,  79.3 ,  69.13,  69.44,  61.47,
        61.5 ,  71.03,  43.76,  59.6 ])

In [52]:
citizen_height

array([2.13, 1.58, 1.61, 1.55, 1.77, 1.61, 1.62, 1.47, 1.43, 1.56, 1.75,
       1.71, 1.54, 1.36, 1.3 , 1.73, 1.87, 1.39, 1.46, 1.4 ])

np.column_stack() func

In [53]:
citizen = np.column_stack((citizen_height,citizen_weight))
citizen

array([[  2.13,  47.41],
       [  1.58,  28.15],
       [  1.61,  92.41],
       [  1.55, 117.85],
       [  1.77,  88.32],
       [  1.61,  20.4 ],
       [  1.62,  48.34],
       [  1.47,  39.04],
       [  1.43,  74.86],
       [  1.56,  89.01],
       [  1.75,  70.84],
       [  1.71,  64.15],
       [  1.54,  79.3 ],
       [  1.36,  69.13],
       [  1.3 ,  69.44],
       [  1.73,  61.47],
       [  1.87,  61.5 ],
       [  1.39,  71.03],
       [  1.46,  43.76],
       [  1.4 ,  59.6 ]])

np.dot() func

In [54]:
matrixA = np.array([[1,2,3],[4,5,6]])
matrixB = np.array([[7,8],[9,10],[11,12]])

np.dot(matrixA,matrixB)   # Dot product of two arrays (matrix multiplication)

array([[ 58,  64],
       [139, 154]])

In [55]:
matrixC = np.array([[1,2,3],[4,5,6]])
matrixD = np.array([[7,8,9],[10,11,12]])

np.multiply(matrixC,matrixD)   # Multiply arguments element-wise.

array([[ 7, 16, 27],
       [40, 55, 72]])

np.transpose() func

In [56]:
np.transpose(matrixA)
# OR
matrixA.T

array([[1, 4],
       [2, 5],
       [3, 6]])

np.linalg.det()

In [57]:
np.linalg.det(np.dot(matrixA,matrixB))   # Compute the determinant of an array.

36.000000000000256

np.linalg.inv()

In [58]:
np.linalg.inv(np.dot(matrixA,matrixB))   # Compute the (multiplicative) inverse of a matrix.

array([[ 4.27777778, -1.77777778],
       [-3.86111111,  1.61111111]])

np.identity()

In [59]:
identityMatrix = np.identity(3)
identityMatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

np.zeros()

In [60]:
zeroMatrix = np.zeros([2,5])
zeroMatrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [62]:
img_array = np.array([
[
[[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5]],
[[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5]],
[[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5]],
[[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5]],
[[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5]],
[[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5],[0.0,1.0,0.5]]
],
[
[[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5]],
[[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5]],
[[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5]],
[[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5]],
[[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5]],
[[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5],[0.0,0.0,0.5]]
]])
img_array.shape    # This is 6x8 RGB image pair (It consists of two different images)

(2, 6, 8, 3)

In [63]:
IMG_SIZE = (6,8)

In [64]:
first_img = img_array[0]
first_img.shape

(6, 8, 3)

In [65]:
def get_img_color(img, size, color=0):     # This function returns a reshaped image array that has only one color option for RGB images
    color_arr = np.zeros(size)
    img = np.array(img)

    # "color" argument is an index of color that represents the color element of the image (R, G, B)
    pixel_cnt = 0  # Pixel of the iamge
    color_ix = 0   # Color index of the pixel

    if len(img.shape) > 3:    # (Row, Column, Color)
        return color_arr
    elif len(img.shape) == 2: # (Row, Column)  -  Already one color
        return img

    for pixel in img:
        for ind in pixel:
            color_arr[pixel_cnt][color_ix] = ind[color]
            color_ix += 1
        pixel_cnt += 1
        color_ix = 0

    return color_arr

In [66]:
first_img_r = get_img_color(first_img, IMG_SIZE, 1)
first_img_r

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [67]:
first_img_r = get_img_color(first_img_r, IMG_SIZE, 1)   # first_img_r is already one color array
first_img_r

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [68]:
import tensorflow as tf

m = [[5, 3], [2,3], [4, 6]]
tf.rank(m)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

tf.reduce_max() method axis must be in the range [-rank(input_tensor),rank(input_tensor))]

In [69]:
tf.reduce_max(m, axis=-1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 3, 6], dtype=int32)>

In [70]:
tf.reduce_max(m, axis=0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>

In [71]:
tf.reduce_max(m, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 3, 6], dtype=int32)>

In [72]:
tf.reduce_max(m, axis=2)

InvalidArgumentError: ignored

The error reason is that the rank of the tensor we give the method is `2`. Plausible values for the axis = `[-1, 0, 1]`.

In [73]:
m = [[[5, 4], [3, 4], [4, 4]], [[2, 4], [3, 4], [5, 4]], [[4, 4], [6, 4], [8, 4]], [[9, 4], [7, 4], [8, 4]]]
tf.rank(m)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [74]:
tf.reduce_max(m, axis=2)  # axis must be in the range [-rank(input_tensor),rank(input_tensor))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[5, 4, 4],
       [4, 4, 5],
       [4, 6, 8],
       [9, 7, 8]], dtype=int32)>